name: kaggle_learn
dependencies:
  - python=3.8.15
  - numpy=1.24.1
  - pandas=1.5.2
  - scipy=1.9.3
  - scikit-learn=1.2.0
  - xgboost=1.7.2
  - pip:
      - python-decouple==3.6
      - kaggle==1.5.12
      - notebook==6.5.2